bug fixed in ca_bimap and spectral bimap
ClemensKohl/CAclust pull request #9
Opened 2022-08-04 16:30 UTC by yanzhaobiomath

modify the function to make it possible to handle with extra input features

2022-08-04 16:42 UTC, ClemensKohl commented on R/biMAP.R
> +      selected_items = selected_items[!duplicated(selected_items)]
If I understand it correctly, what you want would be 
`selected_items = unique(selected_items)`
but I guess it has the same endresult.

2022-08-04 16:46 UTC, ClemensKohl commented on R/biMAP.R
> +  print(dim(umap_coords))
Please remove the print statements

2022-08-04 16:52 UTC, ClemensKohl commented on R/biMAP.R
> +      genec = genec[!duplicated(genec)]
If I understand it correctly, what you want would be 
`selected_items = unique(selected_items)`
but I guess it has the same endresult.
Same for line 99

2022-08-04 16:56 UTC, ClemensKohl requested changes
Just remove the print() statements please, the rest is just a (cosmetic) suggestion.

2022-08-05 08:33 UTC, yanzhaobiomath commented on R/biMAP.R
> +  print(dim(umap_coords))
clear

2022-08-05 08:33 UTC, yanzhaobiomath commented on R/biMAP.R
> +      genec = genec[!duplicated(genec)]
done

2022-08-08 07:25 UTC, ClemensKohl approved these changes
Awesome, thanks a lot :)

2022-08-08 07:26 UTC, merged